language: node_js
node_js:
  - "6.9.1"
services:
  - mongodb
install:
  - npm install
after_failure:
  - find $HOME ! \( -type d \) -name node-dev -exec ls -lah {} \;
script:
  - npm test
  - npm run cucumber
