language: node_js
node_js:
  - "6.9.1"
services:
  - mongodb
install:
  - npm install -g bower
  - bower install
  - npm install
  - chmod +x node_modules/.bin/*
script:
  - npm test
  - npm run cucumber
after_failure:
  - find $HOME ! \( -type d \) -name node-dev -exec ls -lah {} \;
