language: node_js
node_js:
  - "6.9.1"
services:
  - mongodb
before_script:
  - chmod a+x node_modules/mocha/bin/_mocha
  - chmod a+x cucumberjs server/features
script:
  - npm install
  - npm test
  - npm run cucumber
