language: node_js
node_js:
- 6.9.1
services:
- mongodb
install:
- npm install -g bower
- bower install
- npm install
- chmod +x node_modules/.bin/*
script:
- npm test
- npm run cucumber
deploy:
  provider: heroku
  api_key:
    secure: fMK/DB1rgcuu68WCzJ5yOkemtd0e3bwIMVyLYzNIxd4b4IknEiGo4ffS4M02568t1QpUHHI98CIUpB6WuK6tS+cSUYFALV/FgPrV1DLKrkF148AQn5xsiuprxs9nGDk6wRNtV32kt5RGvSZbtOqo7Lp7Dh8tskoApRuEmTlidDKyQzUSFlfYND0GBnx+6vwc1ogcMdHfo9dF2MiKz+JsNrSaW8SrUh971dDv1R+pEf1+9MXOxu5fwvhTm8Dv0b9rhAGmlJU3dRKeebzEvqzaTGV/ogU7nf39+nxSlQyml74YP1IJeLTETpGSG/L6AJ8JYnaveGAsRPvnqoWQJ68lnZr+u0NRqG0z9ZEhvZeIDWfmNXc9JBhvkgueq2fhK8DgzrZJR4QREPjqn+BBeNIwP64WtjAavxji7vpAZbDWefLoFKYhFpwPiwieTVcgvAfwTwP01WMtlCIptEMEni+4jHVsK1SJuwXGLZqCTJwIP41iT3q4yrlYjT9eVkb4XCcNnIm9NmbnNaAuY1+hk0hV2do8Z1zeFCeUDvQHw9VzuKV4o0RCeat/Dij2g/i4PvRdsQwKAncrqdpYg8emQ7yQNZeEAZPvvqRqibH4VauueYR4JiQQxWYgO3vh/r5ficO/MHIZ4b5ZITU+OBoiQ18kwQ8NeOLv/XkhO4SR5j0f558=
  app: kole-api
  on:
    repo: Silverkeytechnology/Kole
after_failure:
- find $HOME ! \( -type d \) -name node-dev -exec ls -lah {} \;
